@echo off
chcp 65001 >nul
echo 正在启动航天知识闯关学习平台...
echo 清理依赖...
"C:\Program Files\Maven\bin\mvn" dependency:purge-local-repository -q
echo 重新构建项目...
"C:\Program Files\Maven\bin\mvn" clean package -DskipTests -q
echo 启动服务器...
"C:\Program Files\Maven\bin\mvn" jetty:run -Djetty.port=8081
pause